export const ADMIN_CREDITS_TEXTS = {
  title: 'Admin - Créditos',
  subtitle: 'Gerencie planos e regras globais de bônus e indicação.',
  planSection: 'CRUD de planos',
  planEditSection: 'Editar plano selecionado',
  configSection: 'Configuracao global',
  createPlan: 'Criar plano',
  editPlan: 'Editar',
  updatePlan: 'Salvar edição',
  cancelPlanEdit: 'Cancelar edição',
  updateConfig: 'Salvar configuracao',
  deletePlan: 'Deletar',
  planCreated: 'Plano criado com sucesso.',
  planUpdated: 'Plano atualizado com sucesso.',
  planCreateError: 'Falha ao criar plano.',
  planUpdateError: 'Falha ao atualizar plano.',
  planDeleted: 'Plano removido.',
  planDeleteError: 'Falha ao remover plano.',
  configUpdated: 'Configuracao atualizada.',
  configUpdateError: 'Falha ao atualizar configuracao.',
} as const;
