export const PROFILE_PAGE_TEXTS = {
  title: 'Perfil do Usuario',
  subtitle: 'Atualize seus dados, senha e foto de perfil.',
  profileCard: 'Dados da conta',
  passwordCard: 'Atualizar senha',
  avatarCard: 'Avatar',
  saveProfile: 'Salvar perfil',
  savePassword: 'Atualizar senha',
  uploadAvatar: 'Enviar avatar',
  referralCodeLabel: 'Codigo de indicacao',
  missingReferralCode: '---',
  selectFileError: 'Selecione um arquivo antes de enviar.',
  profileUpdated: 'Perfil atualizado com sucesso.',
  profileUpdateError: 'Nao foi possivel atualizar o perfil.',
  passwordUpdated: 'Senha atualizada com sucesso.',
  passwordUpdateError: 'Falha ao atualizar senha.',
  avatarUpdated: 'Avatar atualizado com sucesso.',
  avatarUploadError: 'Falha ao enviar avatar.',
} as const;
