export const ADMIN_USERS_TEXTS = {
  title: 'Gestão de usuários',
  subtitle:
    'Gerencie contas com CRUD completo, paginação e controle de role (usuário/admin).',
  createSection: 'Criar usuário',
  editSection: 'Editar usuário selecionado',
  emptyEditSection: 'Selecione um usuário na tabela para editar.',
  tableSection: 'Lista paginada de usuários',
  usernameLabel: 'Nome de usuário',
  emailLabel: 'Email',
  passwordLabel: 'Senha forte',
  roleLabel: 'Perfil',
  createButton: 'Criar usuário',
  updateButton: 'Salvar edição',
  cancelEditButton: 'Cancelar edição',
  editAction: 'Editar',
  deleteAction: 'Excluir',
  promoteAction: 'Promover para admin',
  demoteAction: 'Rebaixar para usuário',
  roleAdmin: 'Administrador',
  roleUser: 'Usuário',
  loading: 'Carregando usuários...',
  noResults: 'Nenhum usuário encontrado.',
  tableHeaders: ['Usuário', 'Email', 'Perfil', 'Ações'],
  createSuccess: 'Usuário criado com sucesso.',
  updateSuccess: 'Usuário atualizado com sucesso.',
  roleSuccess: 'Perfil atualizado com sucesso.',
  deleteSuccess: 'Usuário excluído com sucesso.',
  genericError: 'Não foi possível concluir a operação.',
} as const;
